apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: jumpstarter-run-command
spec:
  params:
    - description: The lease ID to use for command execution.
      name: jmp-lease-id
      type: string
    - default: 'default'
      description: The client config to use.
      name: client-name
      type: string
    - description: The commands to run.
      name: jmp-jScript
      type: string
    
  steps:
    - computeResources: {}
      image: 'quay.io/jumpstarter-dev/jumpstarter:latest'
      name: jmp-run-command
      script: |
        #!/bin/bash
        set -eux

        # Use to the specified Jumpstarter client configuration
        jmp client config use "$(params.client-name)"
        echo "Using Jumpstarter client configuration: $(params.client-name)"

        # Set the Jumpstarter lease environment variable
        export JMP_LEASE="$(params.jmp-lease-id)"

        # Show the command that will be executed
        echo "Running: $(params.jmp-jScript)"

        cd /workspace/source
        ls -la

        # Execute the script commands within the Jumpstarter shell
        jmp client shell <<-EOF
          $(params.jmp-jScript)
        EOF

        echo "The jScript commands were successfully executed."
  workspaces:
    - description: Workspace for mounting Jumpstarter client files.
      mountPath: /root/.config/jumpstarter/clients
      name: jumpstarter-client-secret
      readOnly: true
    - description: Workspace containing the source code / build images
      name: source